version: '3.8'

services:
  web:
    image: ${DOCKER_IMAGE_NAME:-coredesk:latest}
    ports:
      - "80:3000"
    volumes:
      - coredesk-data:/app/data
    restart: always
    environment:
      - NODE_ENV=production
      - JWT_SECRET

volumes:
  coredesk-data:
